export type Product = {
  legacyId: number;
  sku: string;
  name: string;
  category: string;
  categorySlug: string;
  ca: string | null;
  description: string | null;
  image: string | null;
  imageNote?: string;
  sourceUrl: string;
  tags: ReadonlyArray<"destaque" | "novo" | "mais-vendido" | "certificado">;
};

/**
 * Inventário local migrado do catálogo público legado da ItaSafety em 14/08/2026.
 * ITA-{legacyId} é um identificador interno de migração, não um SKU comercial publicado.
 * CA, descrição e imagem permanecem nulos quando a fonte legada não os fornece.
 */
const LEGACY_CATALOG_PRODUCTS: ReadonlyArray<Product> = [
  {
    legacyId: 605,
    sku: "ITA-605",
    name: "21200 Luva Latex Verniz Silver Amarela",
    category: "Luvas",
    categorySlug: "luvas",
    ca: null,
    description: null,
    image: "/images/catalog/products/605.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=605",
    tags: [],
  },
  {
    legacyId: 606,
    sku: "ITA-606",
    name: "21201 Luva Latex Verniz Silver Azul",
    category: "Luvas",
    categorySlug: "luvas",
    ca: null,
    description: null,
    image: "/images/catalog/products/606.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=606",
    tags: [],
  },
  {
    legacyId: 607,
    sku: "ITA-607",
    name: "21401 Luva Latex Longa Ranhurada",
    category: "Luvas",
    categorySlug: "luvas",
    ca: null,
    description: null,
    image: "/images/catalog/products/607.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=607",
    tags: [],
  },
  {
    legacyId: 544,
    sku: "ITA-544",
    name: "42003 Fita Zebrada P/A 200mt",
    category: "Sinalização",
    categorySlug: "sinalizacao",
    ca: null,
    description: null,
    image: "/images/catalog/products/544.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=544",
    tags: [],
  },
  {
    legacyId: 540,
    sku: "ITA-540",
    name: "707 Sapato ocupacional ANTI DERRAPANTE Stick Shoe WOMAN",
    category: "Calçados",
    categorySlug: "calcados",
    ca: "39848",
    description:
      "O STICKY SHOES WOMAN é um calçado ocupacional tecnicamente desenvolvido para pisos lisos que estejam molhados, ensaboados e engordurados ao mesmo tempo. Este modelo é ideal para as profissionais que buscam mais proteção e conforto em longas jornadas de trab…",
    image: "/images/catalog/products/540.png",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=540",
    tags: [],
  },
  {
    legacyId: 539,
    sku: "ITA-539",
    name: "708 Sapato ocupacional ANTI DERRAPANTE Stick Shoe MAN",
    category: "Calçados",
    categorySlug: "calcados",
    ca: "39674",
    description:
      "O STICKY SHOES MAN é um calçado ocupacional tecnicamente desenvolvido para pisos lisos que estejam molhados, ensaboados e engordurados ao mesmo tempo. Este modelo é ideal para as profissionais que buscam mais proteção e conforto em longas jornadas de trabal…",
    image: "/images/catalog/products/539.png",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=539",
    tags: [],
  },
  {
    legacyId: 566,
    sku: "ITA-566",
    name: "Avental de raspa inteiro",
    category: "Diversos",
    categorySlug: "diversos",
    ca: null,
    description: null,
    image: "/images/catalog/products/566.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=566",
    tags: [],
  },
  {
    legacyId: 567,
    sku: "ITA-567",
    name: "Avental de raspa tipo barbeiro",
    category: "Diversos",
    categorySlug: "diversos",
    ca: null,
    description: null,
    image: "/images/catalog/products/567.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=567",
    tags: [],
  },
  {
    legacyId: 506,
    sku: "ITA-506",
    name: "Avental Trevira KP1000",
    category: "Impermeáveis",
    categorySlug: "impermeaveis",
    ca: null,
    description: null,
    image: "/images/catalog/products/506.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=506",
    tags: [],
  },
  {
    legacyId: 542,
    sku: "ITA-542",
    name: "Bandeirola de sinalização",
    category: "Sinalização",
    categorySlug: "sinalizacao",
    ca: null,
    description: null,
    image: "/images/catalog/products/542.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=542",
    tags: [],
  },
  {
    legacyId: 565,
    sku: "ITA-565",
    name: "Blusão de raspa",
    category: "Diversos",
    categorySlug: "diversos",
    ca: null,
    description: null,
    image: "/images/catalog/products/565.png",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=565",
    tags: [],
  },
  {
    legacyId: 614,
    sku: "ITA-614",
    name: "Bota de borracha sem forro Mod Trator",
    category: "Calçados",
    categorySlug: "calcados",
    ca: "3535",
    description: null,
    image: "/images/catalog/products/614.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=614",
    tags: [],
  },
  {
    legacyId: 622,
    sku: "ITA-622",
    name: "Bota de pvc cano curto Acquaflex Baracol",
    category: "Calçados",
    categorySlug: "calcados",
    ca: "37456",
    description: null,
    image: "/images/catalog/products/622.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=622",
    tags: [],
  },
  {
    legacyId: 643,
    sku: "ITA-643",
    name: "BOTA FRIGORIF BRANCA C/FORRO BS71",
    category: "Frigorífica",
    categorySlug: "frigorifica",
    ca: null,
    description: null,
    image: "/images/catalog/products/643.png",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=643",
    tags: [],
  },
  {
    legacyId: 619,
    sku: "ITA-619",
    name: "Bota pvc extra curta Bracol",
    category: "Calçados",
    categorySlug: "calcados",
    ca: "37456",
    description: null,
    image: "/images/catalog/products/619.png",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=619",
    tags: [],
  },
  {
    legacyId: 628,
    sku: "ITA-628",
    name: "Botina cadarço Bi-densidade vaqueta BV51",
    category: "Calçados",
    categorySlug: "calcados",
    ca: "7236",
    description: null,
    image: "/images/catalog/products/628.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=628",
    tags: [],
  },
  {
    legacyId: 629,
    sku: "ITA-629",
    name: "Botina elástico Bi-densidade vaqueta BV52",
    category: "Calçados",
    categorySlug: "calcados",
    ca: "44637",
    description: null,
    image: "/images/catalog/products/629.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=629",
    tags: ["destaque"],
  },
  {
    legacyId: 578,
    sku: "ITA-578",
    name: "Calça Frigorífica Nylon -35º",
    category: "Frigorífica",
    categorySlug: "frigorifica",
    ca: null,
    description: null,
    image: "/images/catalog/products/578-reference.webp",
    imageNote: "Imagem ilustrativa de produto equivalente",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=578",
    tags: [],
  },
  {
    legacyId: 645,
    sku: "ITA-645",
    name: "Cantoneira autoadesivo zebrada em E.V.A",
    category: "Diversos",
    categorySlug: "diversos",
    ca: null,
    description: null,
    image: "/images/catalog/products/645.png",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=645",
    tags: [],
  },
  {
    legacyId: 641,
    sku: "ITA-641",
    name: "Capa de chuva descartavel",
    category: "Descartáveis",
    categorySlug: "descartaveis",
    ca: null,
    description: null,
    image: "/images/catalog/products/641.png",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=641",
    tags: [],
  },
  {
    legacyId: 508,
    sku: "ITA-508",
    name: "Capa pvc forrada c/manga",
    category: "Impermeáveis",
    categorySlug: "impermeaveis",
    ca: null,
    description: null,
    image: "/images/catalog/products/508.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=508",
    tags: [],
  },
  {
    legacyId: 574,
    sku: "ITA-574",
    name: "Capacete Aba Frontal Master II",
    category: "Capacetes",
    categorySlug: "capacetes",
    ca: null,
    description: null,
    image: "/images/catalog/products/574.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=574",
    tags: ["destaque"],
  },
  {
    legacyId: 579,
    sku: "ITA-579",
    name: "Capuz de suedine",
    category: "Frigorífica",
    categorySlug: "frigorifica",
    ca: null,
    description: null,
    image: "/images/catalog/products/579.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=579",
    tags: [],
  },
  {
    legacyId: 638,
    sku: "ITA-638",
    name: "CINTO LOMBAR ERGONOMICO CARGO C/REG",
    category: "Diversos",
    categorySlug: "diversos",
    ca: null,
    description: null,
    image: "/images/catalog/products/638.png",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=638",
    tags: [],
  },
  {
    legacyId: 548,
    sku: "ITA-548",
    name: "Cone pvc injetado",
    category: "Sinalização",
    categorySlug: "sinalizacao",
    ca: null,
    description: null,
    image: "/images/catalog/products/548.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=548",
    tags: ["destaque"],
  },
  {
    legacyId: 563,
    sku: "ITA-563",
    name: "Corrente Plástica P/A IS477",
    category: "Sinalização",
    categorySlug: "sinalizacao",
    ca: null,
    description: null,
    image: "/images/catalog/products/563.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=563",
    tags: [],
  },
  {
    legacyId: 615,
    sku: "ITA-615",
    name: "Creme MAVBIO Mavaro Bisnaga 120gr",
    category: "Creme de Proteção",
    categorySlug: "creme-protecao",
    ca: null,
    description: null,
    image: "/images/catalog/products/615.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=615",
    tags: [],
  },
  {
    legacyId: 562,
    sku: "ITA-562",
    name: "Creme protetor PM1000 Bisnaga com 200gr",
    category: "Creme de Proteção",
    categorySlug: "creme-protecao",
    ca: null,
    description: null,
    image: "/images/catalog/products/562.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=562",
    tags: [],
  },
  {
    legacyId: 559,
    sku: "ITA-559",
    name: "Creme protetor PM1000 pote 200gr",
    category: "Creme de Proteção",
    categorySlug: "creme-protecao",
    ca: null,
    description: null,
    image: "/images/catalog/products/559.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=559",
    tags: [],
  },
  {
    legacyId: 576,
    sku: "ITA-576",
    name: "Creme protetor PM50 Bisnaga 150gr",
    category: "Creme de Proteção",
    categorySlug: "creme-protecao",
    ca: null,
    description: null,
    image: "/images/catalog/products/576.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=576",
    tags: [],
  },
  {
    legacyId: 577,
    sku: "ITA-577",
    name: "Creme protetor PM50 Pote 250gr",
    category: "Creme de Proteção",
    categorySlug: "creme-protecao",
    ca: null,
    description: null,
    image: "/images/catalog/products/577.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=577",
    tags: [],
  },
  {
    legacyId: 580,
    sku: "ITA-580",
    name: "Fita adesiva p/dedos IS105V",
    category: "Diversos",
    categorySlug: "diversos",
    ca: null,
    description: null,
    image: "/images/catalog/products/580.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=580",
    tags: [],
  },
  {
    legacyId: 611,
    sku: "ITA-611",
    name: "IS03CPD Oculos cinza mod Panda",
    category: "Proteção Visual",
    categorySlug: "protecao-visual",
    ca: null,
    description: null,
    image: "/images/catalog/products/611.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=611",
    tags: [],
  },
  {
    legacyId: 612,
    sku: "ITA-612",
    name: "IS03IPD Oculos incolor mod Panda",
    category: "Proteção Visual",
    categorySlug: "protecao-visual",
    ca: null,
    description: null,
    image: "/images/catalog/products/612.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=612",
    tags: [],
  },
  {
    legacyId: 549,
    sku: "ITA-549",
    name: "IS2120 Luva Nitrilica Flocada",
    category: "Luvas",
    categorySlug: "luvas",
    ca: null,
    description: null,
    image: "/images/catalog/products/549.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=549",
    tags: ["destaque"],
  },
  {
    legacyId: 571,
    sku: "ITA-571",
    name: "IS2121 Luva Nitrilica Longa",
    category: "Luvas",
    categorySlug: "luvas",
    ca: null,
    description: null,
    image: "/images/catalog/products/571.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=571",
    tags: [],
  },
  {
    legacyId: 604,
    sku: "ITA-604",
    name: "IS2130 Luva Nitrilica Sem Forro",
    category: "Luvas",
    categorySlug: "luvas",
    ca: null,
    description: null,
    image: "/images/catalog/products/604.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=604",
    tags: [],
  },
  {
    legacyId: 547,
    sku: "ITA-547",
    name: "IS312GW Máscara de solda 12",
    category: "Solda e Facial",
    categorySlug: "solda-facial",
    ca: null,
    description: null,
    image: "/images/catalog/products/547.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=547",
    tags: [],
  },
  {
    legacyId: 545,
    sku: "ITA-545",
    name: "IS913GW Máscara de solda 9a13",
    category: "Solda e Facial",
    categorySlug: "solda-facial",
    ca: null,
    description: null,
    image: "/images/catalog/products/545.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=545",
    tags: [],
  },
  {
    legacyId: 546,
    sku: "ITA-546",
    name: "IS914GW Máscara de solda 9a14",
    category: "Solda e Facial",
    categorySlug: "solda-facial",
    ca: null,
    description: null,
    image: "/images/catalog/products/546.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=546",
    tags: [],
  },
  {
    legacyId: 531,
    sku: "ITA-531",
    name: "ISS05V Oculos verde Ton 3",
    category: "Proteção Visual",
    categorySlug: "protecao-visual",
    ca: null,
    description: null,
    image: "/images/catalog/products/531.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=531",
    tags: [],
  },
  {
    legacyId: 609,
    sku: "ITA-609",
    name: "ISS05V5 Oculos Verde Ton 5",
    category: "Proteção Visual",
    categorySlug: "protecao-visual",
    ca: null,
    description: null,
    image: "/images/catalog/products/609.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=609",
    tags: [],
  },
  {
    legacyId: 541,
    sku: "ITA-541",
    name: "ISS07 Óculos IN-OUT",
    category: "Proteção Visual",
    categorySlug: "protecao-visual",
    ca: "27534",
    description: null,
    image: "/images/catalog/products/541.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=541",
    tags: ["destaque"],
  },
  {
    legacyId: 507,
    sku: "ITA-507",
    name: "Japona Frigorifica Nylon Forrada",
    category: "Frigorífica",
    categorySlug: "frigorifica",
    ca: null,
    description: null,
    image: "/images/catalog/products/507.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=507",
    tags: ["destaque"],
  },
  {
    legacyId: 603,
    sku: "ITA-603",
    name: "Luva Confortex verde",
    category: "Luvas",
    categorySlug: "luvas",
    ca: null,
    description: null,
    image: "/images/catalog/products/603.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=603",
    tags: [],
  },
  {
    legacyId: 551,
    sku: "ITA-551",
    name: "Luva de procedimento latex",
    category: "Luvas",
    categorySlug: "luvas",
    ca: null,
    description: null,
    image: "/images/catalog/products/551.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=551",
    tags: [],
  },
  {
    legacyId: 647,
    sku: "ITA-647",
    name: "Luva de PVC Forrada palma aspera",
    category: "Luvas",
    categorySlug: "luvas",
    ca: null,
    description: null,
    image: "/images/catalog/products/647.png",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=647",
    tags: [],
  },
  {
    legacyId: 582,
    sku: "ITA-582",
    name: "Luva de raspa c/ref interno",
    category: "Luvas",
    categorySlug: "luvas",
    ca: null,
    description: null,
    image: "/images/catalog/products/582.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=582",
    tags: [],
  },
  {
    legacyId: 554,
    sku: "ITA-554",
    name: "Luva de vaqueta petroleira",
    category: "Luvas",
    categorySlug: "luvas",
    ca: null,
    description: null,
    image: "/images/catalog/products/554.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=554",
    tags: [],
  },
  {
    legacyId: 616,
    sku: "ITA-616",
    name: "Luva de vaqueta petroleira punho 20cm de raspa",
    category: "Luvas",
    categorySlug: "luvas",
    ca: null,
    description: null,
    image: "/images/catalog/products/616.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=616",
    tags: [],
  },
  {
    legacyId: 624,
    sku: "ITA-624",
    name: "Luva de vinil sem pó Talge",
    category: "Luvas",
    categorySlug: "luvas",
    ca: null,
    description: null,
    image: "/images/catalog/products/624.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=624",
    tags: [],
  },
  {
    legacyId: 557,
    sku: "ITA-557",
    name: "Luva malha de aço 5 dedos",
    category: "Luvas",
    categorySlug: "luvas",
    ca: null,
    description: null,
    image: "/images/catalog/products/557.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=557",
    tags: [],
  },
  {
    legacyId: 558,
    sku: "ITA-558",
    name: "Luva malha tricot pigmentada",
    category: "Luvas",
    categorySlug: "luvas",
    ca: null,
    description: null,
    image: "/images/catalog/products/558.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=558",
    tags: [],
  },
  {
    legacyId: 588,
    sku: "ITA-588",
    name: "Macacão Branco Newprot S100",
    category: "Vestimenta de Proteção",
    categorySlug: "vestimenta",
    ca: null,
    description: null,
    image: "/images/catalog/products/588-reference.jpg",
    imageNote: "Imagem ilustrativa de produto equivalente",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=588",
    tags: [],
  },
  {
    legacyId: 589,
    sku: "ITA-589",
    name: "Macacão Inter Prot Branco IP280",
    category: "Vestimenta de Proteção",
    categorySlug: "vestimenta",
    ca: null,
    description: null,
    image: "/images/catalog/products/589.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=589",
    tags: [],
  },
  {
    legacyId: 601,
    sku: "ITA-601",
    name: "Mangote de lona punho malha IS71301",
    category: "Diversos",
    categorySlug: "diversos",
    ca: null,
    description: null,
    image: "/images/catalog/products/601.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=601",
    tags: [],
  },
  {
    legacyId: 585,
    sku: "ITA-585",
    name: "Mangote de Raspa IS73300",
    category: "Diversos",
    categorySlug: "diversos",
    ca: null,
    description: null,
    image: "/images/catalog/products/585.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=585",
    tags: [],
  },
  {
    legacyId: 569,
    sku: "ITA-569",
    name: "Meião de Algodão Cru 81040",
    category: "Frigorífica",
    categorySlug: "frigorifica",
    ca: null,
    description: null,
    image: "/images/catalog/products/569.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=569",
    tags: [],
  },
  {
    legacyId: 536,
    sku: "ITA-536",
    name: "Óculos cinza ISS02C",
    category: "Proteção Visual",
    categorySlug: "protecao-visual",
    ca: null,
    description: null,
    image: "/images/catalog/products/536.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=536",
    tags: [],
  },
  {
    legacyId: 530,
    sku: "ITA-530",
    name: "Oculos cinza ISS05C",
    category: "Proteção Visual",
    categorySlug: "protecao-visual",
    ca: null,
    description: null,
    image: "/images/catalog/products/530.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=530",
    tags: [],
  },
  {
    legacyId: 553,
    sku: "ITA-553",
    name: "Óculos Delta incolor",
    category: "Proteção Visual",
    categorySlug: "protecao-visual",
    ca: null,
    description: null,
    image: "/images/catalog/products/553.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=553",
    tags: [],
  },
  {
    legacyId: 552,
    sku: "ITA-552",
    name: "Óculos Evolution incolor",
    category: "Proteção Visual",
    categorySlug: "protecao-visual",
    ca: null,
    description: null,
    image: "/images/catalog/products/552.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=552",
    tags: [],
  },
  {
    legacyId: 623,
    sku: "ITA-623",
    name: "Oculos incolor ampla visão V-maxx",
    category: "Proteção Visual",
    categorySlug: "protecao-visual",
    ca: null,
    description: null,
    image: "/images/catalog/products/623.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=623",
    tags: [],
  },
  {
    legacyId: 533,
    sku: "ITA-533",
    name: "Óculos incolor ISS01I",
    category: "Proteção Visual",
    categorySlug: "protecao-visual",
    ca: null,
    description: null,
    image: "/images/catalog/products/533.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=533",
    tags: [],
  },
  {
    legacyId: 529,
    sku: "ITA-529",
    name: "Oculos incolor ISS05I",
    category: "Proteção Visual",
    categorySlug: "protecao-visual",
    ca: null,
    description: null,
    image: "/images/catalog/products/529.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=529",
    tags: [],
  },
  {
    legacyId: 532,
    sku: "ITA-532",
    name: "Óculos in-out ISS05IE",
    category: "Proteção Visual",
    categorySlug: "protecao-visual",
    ca: null,
    description: null,
    image: "/images/catalog/products/532.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=532",
    tags: [],
  },
  {
    legacyId: 534,
    sku: "ITA-534",
    name: "Oculos Leopardo incolor",
    category: "Proteção Visual",
    categorySlug: "protecao-visual",
    ca: null,
    description: null,
    image: "/images/catalog/products/534.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=534",
    tags: [],
  },
  {
    legacyId: 535,
    sku: "ITA-535",
    name: "Óculos verde ISS09LPV",
    category: "Proteção Visual",
    categorySlug: "protecao-visual",
    ca: null,
    description: null,
    image: "/images/catalog/products/535.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=535",
    tags: [],
  },
  {
    legacyId: 526,
    sku: "ITA-526",
    name: "Palmilha de silicone plana",
    category: "Calçados",
    categorySlug: "calcados",
    ca: null,
    description:
      "DESCRIÇÃO : Palmilha de silicone plana SILICENTER Palmilha 100% silicone plana SILICENTER para descanso e conforto dos pés causados pelo atrito durante o caminhar, dores nos joelhos e também indicado para atividades esportivas. Alivia o impacto na mar…",
    image: "/images/catalog/products/526.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=526",
    tags: [],
  },
  {
    legacyId: 527,
    sku: "ITA-527",
    name: "Palmilha em EVA",
    category: "Calçados",
    categorySlug: "calcados",
    ca: null,
    description:
      "DESCRIÇÃO : Palmilha de conforto em etileno-acetato de vinil (EVA), revestida com tecido de poliéster, com componentes anti-bactericidas, fungicidas e de redução de odores. Marca Arteflex Cód: IS700E Cor: Branca Tamanhos: 33 ao 46",
    image: "/images/catalog/products/527.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=527",
    tags: [],
  },
  {
    legacyId: 528,
    sku: "ITA-528",
    name: "Palmilha em EVA termoconformada",
    category: "Calçados",
    categorySlug: "calcados",
    ca: null,
    description:
      "DESCRIÇÃO : Palmilha de conforto para calçado de segurança fabricada em e.v.a. termo conformada anatomicamente, com proteção anti-bacteriana que previne o aparecimento de bactérias causadoras de odores indesejados. Aumenta a vida útil do calçado. TAMANH…",
    image: "/images/catalog/products/528.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=528",
    tags: [],
  },
  {
    legacyId: 640,
    sku: "ITA-640",
    name: "Pedestal Organizador de Fila IS47850",
    category: "Diversos",
    categorySlug: "diversos",
    ca: null,
    description: null,
    image: "/images/catalog/products/640.png",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=640",
    tags: [],
  },
  {
    legacyId: 564,
    sku: "ITA-564",
    name: "Pedestal Plástico",
    category: "Sinalização",
    categorySlug: "sinalizacao",
    ca: null,
    description: null,
    image: "/images/catalog/products/564.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=564",
    tags: [],
  },
  {
    legacyId: 630,
    sku: "ITA-630",
    name: "Perneira de raspa fecham velcro",
    category: "Diversos",
    categorySlug: "diversos",
    ca: null,
    description: null,
    image: "/images/catalog/products/630.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=630",
    tags: [],
  },
  {
    legacyId: 646,
    sku: "ITA-646",
    name: "Protetor de impacto zebrado em E.V.A",
    category: "Diversos",
    categorySlug: "diversos",
    ca: null,
    description: null,
    image: "/images/catalog/products/646.png",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=646",
    tags: [],
  },
  {
    legacyId: 597,
    sku: "ITA-597",
    name: "Protetor Facial Anatomico Incolor",
    category: "Solda e Facial",
    categorySlug: "solda-facial",
    ca: null,
    description: null,
    image: "/images/catalog/products/597.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=597",
    tags: [],
  },
  {
    legacyId: 598,
    sku: "ITA-598",
    name: "Protetor Facial Anatomico Verde",
    category: "Solda e Facial",
    categorySlug: "solda-facial",
    ca: null,
    description: null,
    image: "/images/catalog/products/598.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=598",
    tags: [],
  },
  {
    legacyId: 599,
    sku: "ITA-599",
    name: "Protetor Facial Incolor 8",
    category: "Solda e Facial",
    categorySlug: "solda-facial",
    ca: null,
    description: null,
    image: "/images/catalog/products/599.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=599",
    tags: ["destaque"],
  },
  {
    legacyId: 637,
    sku: "ITA-637",
    name: "Protetor Facial Incolor Policarbonato 9",
    category: "Solda e Facial",
    categorySlug: "solda-facial",
    ca: null,
    description: null,
    image: "/images/catalog/products/637.png",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=637",
    tags: [],
  },
  {
    legacyId: 568,
    sku: "ITA-568",
    name: "Protetor plug descart c/cordão 3M",
    category: "Proteção Auditiva",
    categorySlug: "protecao-auditiva",
    ca: null,
    description: null,
    image: "/images/catalog/products/568.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=568",
    tags: [],
  },
  {
    legacyId: 560,
    sku: "ITA-560",
    name: "Protetor Plug Silicone cordão poliprop",
    category: "Proteção Auditiva",
    categorySlug: "protecao-auditiva",
    ca: null,
    description: null,
    image: "/images/catalog/products/560.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=560",
    tags: [],
  },
  {
    legacyId: 561,
    sku: "ITA-561",
    name: "Protetor Plug Silicone cordão silic",
    category: "Proteção Auditiva",
    categorySlug: "protecao-auditiva",
    ca: null,
    description: null,
    image: "/images/catalog/products/561.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=561",
    tags: [],
  },
  {
    legacyId: 592,
    sku: "ITA-592",
    name: "Respirador descart PFF1 CO sem valvula",
    category: "Proteção Respiratória",
    categorySlug: "protecao-respiratoria",
    ca: null,
    description: null,
    image: "/images/catalog/products/592.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=592",
    tags: [],
  },
  {
    legacyId: 591,
    sku: "ITA-591",
    name: "Respirador descart PFF1 com valvula",
    category: "Proteção Respiratória",
    categorySlug: "protecao-respiratoria",
    ca: null,
    description: null,
    image: "/images/catalog/products/591.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=591",
    tags: [],
  },
  {
    legacyId: 590,
    sku: "ITA-590",
    name: "Respirador descart PFF1 sem valvula",
    category: "Proteção Respiratória",
    categorySlug: "protecao-respiratoria",
    ca: null,
    description: null,
    image: "/images/catalog/products/590.png",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=590",
    tags: ["destaque"],
  },
  {
    legacyId: 596,
    sku: "ITA-596",
    name: "Respirador descart PFF2 CO com valvula",
    category: "Proteção Respiratória",
    categorySlug: "protecao-respiratoria",
    ca: null,
    description: null,
    image: "/images/catalog/products/596.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=596",
    tags: [],
  },
  {
    legacyId: 595,
    sku: "ITA-595",
    name: "Respirador descart PFF2 CO sem valvula",
    category: "Proteção Respiratória",
    categorySlug: "protecao-respiratoria",
    ca: null,
    description: null,
    image: "/images/catalog/products/595.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=595",
    tags: [],
  },
  {
    legacyId: 594,
    sku: "ITA-594",
    name: "Respirador descart PFF2 com valvula",
    category: "Proteção Respiratória",
    categorySlug: "protecao-respiratoria",
    ca: null,
    description: null,
    image: "/images/catalog/products/594.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=594",
    tags: [],
  },
  {
    legacyId: 593,
    sku: "ITA-593",
    name: "Respirador descart PFF2 sem valvula",
    category: "Proteção Respiratória",
    categorySlug: "protecao-respiratoria",
    ca: null,
    description: null,
    image: "/images/catalog/products/593.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=593",
    tags: [],
  },
  {
    legacyId: 627,
    sku: "ITA-627",
    name: "Sapato cadarço bi-densidade vaqueta SV60",
    category: "Calçados",
    categorySlug: "calcados",
    ca: "4642",
    description: null,
    image: "/images/catalog/products/627.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=627",
    tags: [],
  },
  {
    legacyId: 626,
    sku: "ITA-626",
    name: "Sapato elástico bi-densidade vaqueta SV62",
    category: "Calçados",
    categorySlug: "calcados",
    ca: "42631",
    description: null,
    image: "/images/catalog/products/626.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=626",
    tags: [],
  },
  {
    legacyId: 635,
    sku: "ITA-635",
    name: "Sapato Elastico Feminino SV66",
    category: "Calçados",
    categorySlug: "calcados",
    ca: null,
    description: null,
    image: "/images/catalog/products/635.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=635",
    tags: [],
  },
  {
    legacyId: 522,
    sku: "ITA-522",
    name: "Sapato Feminino de elástico com biqueira de aço",
    category: "Calçados",
    categorySlug: "calcados",
    ca: "27937",
    description:
      "DESCRIÇÃO: Sapato de segurança (Feminino) confeccionado em couro soft relax de alta qualidade com curtimento atravessado, 1,4/1,6 mm linha de espessura.",
    image: "/images/catalog/products/522.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=522",
    tags: [],
  },
  {
    legacyId: 520,
    sku: "ITA-520",
    name: "Sapato Feminio de amarrar com biqueira de aço",
    category: "Calçados",
    categorySlug: "calcados",
    ca: "27937",
    description:
      "DESCRIÇÃO: Sapato Feminino de amarrar com biqueira de aço Confeccionada em Couro Soft de alta qualidade com curtimento atravessado, 1,4/1,6 mm linhas de espessura, hidrofugado , forro em tecido antimicrobiano com alta respirabilidade, palmilha montada sis…",
    image: "/images/catalog/products/520.jpg",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=520",
    tags: [],
  },
  {
    legacyId: 639,
    sku: "ITA-639",
    name: "Suporte de punho elástico Digitador E100E100",
    category: "Diversos",
    categorySlug: "diversos",
    ca: null,
    description: null,
    image: "/images/catalog/products/639.png",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=639",
    tags: [],
  },
  {
    legacyId: 644,
    sku: "ITA-644",
    name: "Tela Tapume Laranja 1.20X50mt",
    category: "Diversos",
    categorySlug: "diversos",
    ca: null,
    description: null,
    image: "/images/catalog/products/644.png",
    sourceUrl: "http://itasafety.com.br/detalhes.php?id=644",
    tags: [],
  },
];

export const LOCAL_CATALOG_PRODUCTS: ReadonlyArray<Product> = LEGACY_CATALOG_PRODUCTS.map(
  (product) => ({
    ...product,
    image: product.image ? `/images/catalog/products-enhanced/${product.legacyId}.webp` : null,
  }),
);

export const FEATURED_PRODUCTS: ReadonlyArray<Product> = LOCAL_CATALOG_PRODUCTS.filter((product) =>
  product.tags.includes("destaque"),
);
